Add ability to manually trigger GH action

diff --git a/.github/workflows/gyb_release.yml b/.github/workflows/gyb_release.yml
--- a/.github/workflows/gyb_release.yml
+++ b/.github/workflows/gyb_release.yml
@@ -3,18 +3,26 @@ name: GYB Release
 on:
   repository_dispatch:
     types: [gyb-release]
+  workflow_dispatch:
+    inputs:
+      tag:
+        description: 'GYB Release Tag'
 
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps: 
       -
-        name: Check if latest release
-        id: current_release
+        name: Check GYB release info
+        id: release_info
         run: |
+          [ -z "${{ github.event.client_payload.tag }}" ] && tag="${{ github.event.inputs.tag }}" || tag="${{ github.event.client_payload.tag }}"
+          [ -z "$tag" ] && { echo "ERROR: No tag passed to workflow'" >&2 && exit 1; }
+          echo "::set-output name=tag::$tag"
+
           latest=`curl -sX GET https://api.github.com/repos/jay0lee/got-your-back/releases/latest \
           | jq -r '.tag_name'`
-          [ "$latest" == "${{ github.event.client_payload.tag }}" ] && islatest="true" || islatest="false"
+          [ "$latest" == "$tag" ] && islatest="true" || islatest="false"
           echo "::set-output name=islatest::$islatest" 
       - 
         name: Checkout
@@ -26,9 +34,9 @@ jobs:
         with:
           images: ghcr.io/awbn/gyb
           flavor: |
-            latest=${{ steps.current_release.outputs.islatest }}
+            latest=${{ steps.release_info.outputs.islatest }}
           tags: |
-            type=semver,pattern={{major}}.{{minor}},value=${{ github.event.client_payload.tag }}
+            type=semver,pattern={{major}}.{{minor}},value=${{ steps.release_info.outputs.tag }}
       - 
         name: Set up QEMU for x-platform
         uses: docker/setup-qemu-action@v1
@@ -41,7 +49,7 @@ jobs:
         uses: docker/build-push-action@v2
         with:
           context: .
-          build-args: GYB_VERSION=${{ github.event.client_payload.tag }}
+          build-args: GYB_VERSION=${{ steps.release_info.outputs.tag }}
           platforms: linux/amd64,linux/arm64,linux/arm/v7
           push: false
           tags: ${{ steps.metadata.outputs.tags }}
